"""added name to bev_post

Revision ID: 7fcd7349e53f
Revises: b3cdc3b431ed
Create Date: 2024-12-08 21:26:22.427894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcd7349e53f'
down_revision = 'b3cdc3b431ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beverage_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beverage_posts', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
